import {
  buttonTheme,
  cardTheme,
  checkboxFieldTheme,
  checkboxTheme,
  comboboxOptionTheme,
  comboboxTheme,
  containerTheme,
  descriptionTheme,
  dialogPanelTheme,
  dialogTheme,
  dialogTitleTheme,
  errorTheme,
  fieldsetnTheme,
  fieldTheme,
  formTheme,
  iconTheme,
  inputTheme,
  labelTheme,
  legendTheme,
  listboxOptionTheme,
  listboxTheme,
  menuButtonTheme,
  menuHeadingTheme,
  menuItemsTheme,
  menuItemTheme,
  menuSectionTheme,
  menuSeparatorTheme,
  menuTheme,
  popoverBackdropTheme,
  popoverButtonTheme,
  popoverGroupTheme,
  popoverPanelTheme,
  popoverTheme,
  radioFieldTheme,
  radioGroupTheme,
  radioTheme,
  spinnerTheme,
  tableBodyTheme,
  tableCaptionTheme,
  tableCellTheme,
  tableFootTheme,
  tableHeaderTheme,
  tableHeadTheme,
  tableRowTheme,
  tableTheme,
  textareaTheme,
  textTheme,
} from '../components.js';
import {createTailwindConfig, createTailwindMerge} from '../development.js';
import {type Theme} from './Theme.js';

export const defaultTheme: Theme = {
  Button: buttonTheme,
  Card: cardTheme,
  Checkbox: checkboxTheme,
  CheckboxField: checkboxFieldTheme,
  Combobox: comboboxTheme,
  ComboboxOption: comboboxOptionTheme,
  Container: containerTheme,
  Description: descriptionTheme,
  Dialog: dialogTheme,
  DialogPanel: dialogPanelTheme,
  DialogTitle: dialogTitleTheme,
  Error: errorTheme,
  Field: fieldTheme,
  Fieldset: fieldsetnTheme,
  Form: formTheme,
  Icon: iconTheme,
  Input: inputTheme,
  Label: labelTheme,
  Legend: legendTheme,
  Listbox: listboxTheme,
  ListboxOption: listboxOptionTheme,
  Menu: menuTheme,
  MenuButton: menuButtonTheme,
  MenuHeading: menuHeadingTheme,
  MenuItem: menuItemTheme,
  MenuItems: menuItemsTheme,
  MenuSection: menuSectionTheme,
  MenuSeparator: menuSeparatorTheme,
  Popover: popoverTheme,
  PopoverBackdrop: popoverBackdropTheme,
  PopoverButton: popoverButtonTheme,
  PopoverGroup: popoverGroupTheme,
  PopoverPanel: popoverPanelTheme,
  Radio: radioTheme,
  RadioField: radioFieldTheme,
  RadioGroup: radioGroupTheme,
  Spinner: spinnerTheme,
  Table: tableTheme,
  TableBody: tableBodyTheme,
  TableCaption: tableCaptionTheme,
  TableCell: tableCellTheme,
  TableFoot: tableFootTheme,
  TableHead: tableHeadTheme,
  TableHeader: tableHeaderTheme,
  TableRow: tableRowTheme,
  Text: textTheme,
  Textarea: textareaTheme,

  merge: createTailwindMerge(createTailwindConfig()),
};
