/**
 * DO NOT EDIT!
 * This file was autogenerated by Carson.
 * Changes may cause incorrect behavior and will be lost when the file is regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

import {type StorybookConfig} from '@storybook/react-vite';
import _ from 'lodash';

const config: StorybookConfig = _.merge(
  {
    stories: ['../stories/**/*.mdx', '../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
    addons: [
      '@chromatic-com/storybook',
      '@storybook/addon-essentials',
      '@storybook/addon-interactions',
      '@storybook/addon-links',
    ],
    framework: {
      name: '@storybook/react-vite',
      options: {},
    },
    docs: {
      autodocs: 'tag',
    },
  } satisfies StorybookConfig,
  {
    stories: [
      '../stories/Introduction.mdx',
      '../stories/**/*.mdx',
      '../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)',
    ],
  },
);

export default config;
