/**
 * This file was autogenerated by Carson.
 * If you edit it, your changes will be preserved. If you delete this file, it will be regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

import {createTailwindConfig} from '../source/development.js';

export const tailwindConfig = createTailwindConfig();
