/**
 * DO NOT EDIT!
 * This file was autogenerated by Carson.
 * Changes may cause incorrect behavior and will be lost when the file is regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

import {defineConfig} from 'tsdown';

export default defineConfig({
  entry: ['source/main.ts'],
  outDir: 'build',
  platform: 'neutral',
  unbundle: true,
});
