/**
 * DO NOT EDIT!
 * This file was autogenerated by Carson.
 * Changes may cause incorrect behavior and will be lost when the file is regenerated.
 *
 * Run `npx carson update workspace` to regenerate.
 */

module.exports = {
  plugin: 'typedoc-plugin-markdown',
  entryPoints: ['./source/main.ts'],
  out: 'docs',
  readme: 'none',
  githubPages: false,
  hideBreadcrumbs: true,
};
